### ISSUE TITLE
unresolved imports `vtkio::export_ascii`, `vtkio::import`

### ISSUE THREAD

**Issue by hunter1992** [elrnv/vtkio#32]
When I tested the import/export example, the following error occurred:

```
error[E0432]: unresolved imports `vtkio::export_ascii`, `vtkio::import`
 --> src/main.rs:2:13
  |
2 | use vtkio::{export_ascii, import};
  |             ^^^^^^^^^^^^  ^^^^^^ no `import` in the root
  |             |
  |             no `export_ascii` in the root
```
 I want to ask how to solve this problem？

**Comment by elrnv** [comment]
Thank you for flagging this! The example in the readme is slightly outdated. I just pushed a commit fixing it. The correct usage is found on [docs.rs](https://docs.rs/vtkio/0.6.3/vtkio/). In general, for Rust libraries, docs.rs is a better source for finding examples because they are often at least compiled with the corresponding revision of the code.
