### ISSUE TITLE
Should `vtkio::Error` implement `std::error::Error`?

### ISSUE THREAD

**Issue by Andlon** [elrnv/vtkio#5]
See title. I think this would make sense and would allow for more rapid prototyping with e.g. functions returning `Box<std::error::Error>`.

I would happily submit a PR (once time permits...) if you agree that this could be useful.

**Comment by elrnv** [comment]
Yes this makes sense to me. I'd be happy to accept a PR for that.
In general, I'm open to contributions that improve compatibility with the rest of the ecosystem.

**Comment by elrnv** [comment]
This was done in 61525fe06970c9cfcb89e85a7fd22bfe4d212552 and published in v0.2.4.
It would also be nice to extend this to `writer::Error` but I moved that into a [separate issue](https://github.com/elrnv/vtkio/issues/6) since it's not as important.

Closing this for now, but happy to accept improvements/adjustments.

**Comment by Andlon** [comment]
Thanks, that's great! I haven't been actively using VTK lately (but I will soon enough), which is why I never got around to contributing the feature myself.
